#!/bin/bash

set -euo pipefail

usage() {
  echo "Usage: $(basename "$0") [<path>]"
  echo
  echo "Where:"
  echo "  path           path to mp3 file"
  echo
  echo "Options:"
  echo "  --help, -h     Show this help."
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --help|-h)
      usage
      ;;
    *)
      if [[ -z "${path+x}" ]]; then
        path="$1"
      else
        echo "Error: unknown argument '$path'."
        echo "Type --help for details."
        exit 1
      fi
      shift
      ;;
  esac
done

if [[ -z "${path+x}" ]]; then
  echo "Error: path not defined."
  echo "Type --help for details."
  exit 1
fi

result=$(ffprobe -v error -print_format json -show_format -show_streams "$path" | jq .format.tags)
echo "$result"
