#!/bin/bash

usage() {
  echo "Usage: $0 <winpid>"
  echo
  echo "Where:"
  echo "  <pattern>  Is the windows process id."
  echo ""
  echo "Return: process id"
  echo ""
  echo "Options:"
  echo "  -h, --help  Show this help."
  exit 1
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  usage
  exit 0
fi

if [ -z "$1" ]; then
  usage
  exit 1
fi

ps -W | awk -v winpid="$1" '$4 == winpid {print $1}'
