#!/bin/bash

set -euo pipefail

task_folder=/e/msys64/home/User/.task

usage() {
  echo "Usage: $(basename "$0") (push|pull|status)"
  echo
  echo "Where:"
  echo "  push        commit and push to remote"
  echo "  pull        pull from remote"
  echo "  status"
  echo
  echo "Options:"
  echo "  --help, -h  Show this help."
  exit 1
}

push() {
  cd $task_folder
  git commit -a -m update
  git push
  exit 0
}

pull() {
  cd $task_folder
  git pull
  exit 0
}

status() {
  cd $task_folder
  git status
  exit 0
}

if [[ $# -eq 0 ]]; then
  usage
  exit 0
fi

while [[ $# -gt 0 ]]; do
  case $1 in
    --help|-h)
      usage
      exit 0
      ;;
    push)
      push
      shift
      ;;
    pull)
      pull
      shift
      ;;
    status)
      status
      shift
      ;;
    *)
      echo "Error: unknown argument '$1'."
      echo "Type --help for details."
      exit 1
      ;;
  esac
done
